# Generated by Django 3.0.8 on 2020-12-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201215_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='username',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following_username',
            new_name='following_user',
        ),
    ]
